# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mixingcheck < Formula
  desc "search,check and update go modules"
  homepage "https://github.com/ormanli/mixingcheck"
  version "1.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/mixingcheck/releases/download/v1.1.0/mixingcheck_Darwin_x86_64.tar.gz"
      sha256 "e41b0d41910eafa103019eb6972c7d27d6e657bcc03871811ccb1242898c331c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ormanli/mixingcheck/releases/download/v1.1.0/mixingcheck_Darwin_arm64.tar.gz"
      sha256 "f8b6f75e6d8df68c0880884e27bc3648c2109502bb2378ac473be9384f319f86"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/mixingcheck/releases/download/v1.1.0/mixingcheck_Linux_x86_64.tar.gz"
      sha256 "64b6742fe64ba27d5b430b46ad124eaeaf364e4aad6cbea12c6d8bd26961a312"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ormanli/mixingcheck/releases/download/v1.1.0/mixingcheck_Linux_arm64.tar.gz"
      sha256 "d141832da5ad8486d7aae6b106d91198b94a7b667df88199c2336ec3869245f7"
    end
  end

  def install
    bin.install "mixingcheck"
  end

  test do
    system "#{bin/mixingcheck}"
  end
end
