name: mixingcheck release
on:
  push:
    tags:
      - "*"

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go (1.15)
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
